[#ftl]
[#-- @implicitly included --]
[#macro file name charset="utf-8"]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#macro]
[#function isFacetExcluded element]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function nameForTypeDefinition typeDefinition]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function classnameFor element]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function findRootElement element]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function xmlFunctionIdentifier element]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function prefix element]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function referencedNamespaces element]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function nameForEnumConstant enumValue]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]