[#ftl]
[#-- @implicitly included --]

[#macro file name package charset="utf-8"]
  [#stop "Should never be called."/]
[/#macro]
[#function packageFor element]
  [#stop "Should never be called."/]
[/#function]
[#function simpleNameFor element params=true]
  [#stop "Should never be called."/]
[/#function]
[#function classnameFor type]
  [#stop "Should never be called."/]
[/#function]
[#function isFacetExcluded hasFacets]
  [#stop "Should never be called."/]
[/#function]
[#function annotationValue annotationMirror elementName="value"]
  [#stop "Should never be called."/]
[/#function]
[#function mediaTypeFor entity]
  [#stop "Should never be called."/]
[/#function]
[#function isAccessorOfTypeLong accessor]
  [#stop "Should never be called."/]
[/#function]