[#ftl]
[#-- @implicitly included --]
[#macro file name charset="utf-8"]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#macro]
[#function datatypeNameFor dataType]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function responsesOf method]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function findBestDataType entity]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function validParametersOf method]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]