[#ftl]
[#-- @implicitly included --]
[#macro file name package="" charset="utf-8"]
[#--this template is here just so Intellij knows there exists a macro named "file".--]
[#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#macro]
[#function isFacetExcluded element]
[#--this template is here just so Intellij knows there exists a macro named "file".--]
[#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function moduleFor element]
[#--this template is here just so Intellij knows there exists a macro named "file".--]
[#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function simpleNameFor element]
[#--this template is here just so Intellij knows there exists a macro named "file".--]
[#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function classnameFor element]
[#--this template is here just so Intellij knows there exists a macro named "file".--]
[#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]