//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.ServiceReference1 {
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(IsNullable=false)]
    public partial class ServiceException : object, System.Xml.Serialization.IXmlSerializable, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("ServiceException", "http://enunciate.codehaus.org/samples/full");
        
        public System.Xml.XmlNode[] Nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public void ReadXml(System.Xml.XmlReader reader) {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer) {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema() {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas) {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("ExportSchema")]
    [System.Xml.Serialization.XmlRootAttribute(ElementName="unknownSourceBean", Namespace="http://enunciate.codehaus.org/samples/full", IsNullable=false)]
    public partial class unknownSourceBean : object, System.Xml.Serialization.IXmlSerializable, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Xml.XmlNode[] nodesField;
        
        private static System.Xml.XmlQualifiedName typeName = new System.Xml.XmlQualifiedName("unknownSourceBean", "");
        
        public System.Xml.XmlNode[] Nodes {
            get {
                return this.nodesField;
            }
            set {
                if ((object.ReferenceEquals(this.nodesField, value) != true)) {
                    this.nodesField = value;
                    this.RaisePropertyChanged("Nodes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        public void ReadXml(System.Xml.XmlReader reader) {
            this.nodesField = System.Runtime.Serialization.XmlSerializableServices.ReadNodes(reader);
        }
        
        public void WriteXml(System.Xml.XmlWriter writer) {
            System.Runtime.Serialization.XmlSerializableServices.WriteNodes(writer, this.Nodes);
        }
        
        public System.Xml.Schema.XmlSchema GetSchema() {
            return null;
        }
        
        public static System.Xml.XmlQualifiedName ExportSchema(System.Xml.Schema.XmlSchemaSet schemas) {
            System.Runtime.Serialization.XmlSerializableServices.AddDefaultSchema(schemas, typeName);
            return typeName;
        }
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Name="source-service", Namespace="http://enunciate.codehaus.org/samples/full", ConfigurationName="ServiceReference1.sourceservice")]
    public interface sourceservice {
        
        // CODEGEN: Parameter 'source' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(assertion))]
        void addSource(ConsoleApplication1.ServiceReference1.addSource request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference1.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference1.unknownSourceBean), Action="", Name="unknownSourceBean")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(assertion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference1.getSourceResponse getSource(ConsoleApplication1.ServiceReference1.getSourceRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference1.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(assertion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference1.addInfoSetResponse addInfoSet(ConsoleApplication1.ServiceReference1.addInfoSetRequest request);
        
        // CODEGEN: Generating message contract since message addEventsRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference1.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(assertion))]
        ConsoleApplication1.ServiceReference1.addEventsResponse addEvents(ConsoleApplication1.ServiceReference1.addEventsRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/cite")]
    public partial class source : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string titleField;
        
        private string linkField;
        
        private infoSet[] infoSetsField;
        
        private repository repositoryField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string link {
            get {
                return this.linkField;
            }
            set {
                this.linkField = value;
                this.RaisePropertyChanged("link");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("infoSets", Order=2)]
        public infoSet[] infoSets {
            get {
                return this.infoSetsField;
            }
            set {
                this.infoSetsField = value;
                this.RaisePropertyChanged("infoSets");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public repository repository {
            get {
                return this.repositoryField;
            }
            set {
                this.repositoryField = value;
                this.RaisePropertyChanged("repository");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/cite")]
    public partial class infoSet : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] inferencesField;
        
        private contributor contributorField;
        
        private string sourceField;
        
        private string sourceReferenceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inferences", DataType="IDREF", Order=0)]
        public string[] inferences {
            get {
                return this.inferencesField;
            }
            set {
                this.inferencesField = value;
                this.RaisePropertyChanged("inferences");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public contributor contributor {
            get {
                return this.contributorField;
            }
            set {
                this.contributorField = value;
                this.RaisePropertyChanged("contributor");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="IDREF", Order=2)]
        public string source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
                this.RaisePropertyChanged("source");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string sourceReference {
            get {
                return this.sourceReferenceField;
            }
            set {
                this.sourceReferenceField = value;
                this.RaisePropertyChanged("sourceReference");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/cite")]
    public partial class contributor : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string contactNameField;
        
        private string emailsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string contactName {
            get {
                return this.contactNameField;
            }
            set {
                this.contactNameField = value;
                this.RaisePropertyChanged("contactName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string emails {
            get {
                return this.emailsField;
            }
            set {
                this.emailsField = value;
                this.RaisePropertyChanged("emails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/cite")]
    public partial class note : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public partial class person : object, System.ComponentModel.INotifyPropertyChanged {
        
        private gender genderField;
        
        private name[] namesField;
        
        private @event[] eventsField;
        
        private fact[] factsField;
        
        private relationship[] relationshipsField;
        
        private byte[] pictureField;
        
        private personEntry[] notesField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public gender gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
                this.RaisePropertyChanged("gender");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("names", Order=1)]
        public name[] names {
            get {
                return this.namesField;
            }
            set {
                this.namesField = value;
                this.RaisePropertyChanged("names");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("events", Order=2)]
        public @event[] events {
            get {
                return this.eventsField;
            }
            set {
                this.eventsField = value;
                this.RaisePropertyChanged("events");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("facts", Order=3)]
        public fact[] facts {
            get {
                return this.factsField;
            }
            set {
                this.factsField = value;
                this.RaisePropertyChanged("facts");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("relationships", Order=4)]
        public relationship[] relationships {
            get {
                return this.relationshipsField;
            }
            set {
                this.relationshipsField = value;
                this.RaisePropertyChanged("relationships");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] picture {
            get {
                return this.pictureField;
            }
            set {
                this.pictureField = value;
                this.RaisePropertyChanged("picture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("entry", IsNullable=false)]
        public personEntry[] notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public partial class gender : assertion {
        
        private genderType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public genderType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public enum genderType {
        
        /// <remarks/>
        m,
        
        /// <remarks/>
        f,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(occurringAssertion))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@event))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(name))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(relationship))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(gender))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public abstract partial class assertion : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string noteField;
        
        private string infoSetField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="IDREF", Order=1)]
        public string infoSet {
            get {
                return this.infoSetField;
            }
            set {
                this.infoSetField = value;
                this.RaisePropertyChanged("infoSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(fact))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(@event))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public abstract partial class occurringAssertion : assertion {
        
        private System.DateTime dateField;
        
        private bool dateFieldSpecified;
        
        private string placeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
                this.RaisePropertyChanged("date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dateSpecified {
            get {
                return this.dateFieldSpecified;
            }
            set {
                this.dateFieldSpecified = value;
                this.RaisePropertyChanged("dateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string place {
            get {
                return this.placeField;
            }
            set {
                this.placeField = value;
                this.RaisePropertyChanged("place");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public partial class fact : occurringAssertion {
        
        private string valueField;
        
        private string descriptionField;
        
        private factType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public factType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public enum factType {
        
        /// <remarks/>
        occupation,
        
        /// <remarks/>
        possessions,
        
        /// <remarks/>
        race,
        
        /// <remarks/>
        nation_of_origin,
        
        /// <remarks/>
        physical_description,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public partial class @event : occurringAssertion {
        
        private string descriptionField;
        
        private eventType typeField;
        
        private bool typeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public eventType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public enum eventType {
        
        /// <remarks/>
        birth,
        
        /// <remarks/>
        christening,
        
        /// <remarks/>
        marriage,
        
        /// <remarks/>
        death,
        
        /// <remarks/>
        burial,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public partial class name : assertion {
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public partial class relationship : assertion {
        
        private string id1Field;
        
        private relationshipType typeField;
        
        private bool typeFieldSpecified;
        
        private name sourcePersonNameField;
        
        private name targetPersonNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("id", Order=0)]
        public string id1 {
            get {
                return this.id1Field;
            }
            set {
                this.id1Field = value;
                this.RaisePropertyChanged("id1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public relationshipType type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool typeSpecified {
            get {
                return this.typeFieldSpecified;
            }
            set {
                this.typeFieldSpecified = value;
                this.RaisePropertyChanged("typeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public name sourcePersonName {
            get {
                return this.sourcePersonNameField;
            }
            set {
                this.sourcePersonNameField = value;
                this.RaisePropertyChanged("sourcePersonName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public name targetPersonName {
            get {
                return this.targetPersonNameField;
            }
            set {
                this.targetPersonNameField = value;
                this.RaisePropertyChanged("targetPersonName");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public enum relationshipType {
        
        /// <remarks/>
        spouse,
        
        /// <remarks/>
        parent,
        
        /// <remarks/>
        child,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://enunciate.codehaus.org/samples/genealogy/data")]
    public partial class personEntry : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string keyField;
        
        private note valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
                this.RaisePropertyChanged("key");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public note value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3053")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://enunciate.codehaus.org/samples/genealogy/cite")]
    public partial class repository : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string locationField;
        
        private string emailField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addSource", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class addSource {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.ServiceReference1.source source;
        
        public addSource() {
        }
        
        public addSource(ConsoleApplication1.ServiceReference1.source source) {
            this.source = source;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSource", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class getSourceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string id;
        
        public getSourceRequest() {
        }
        
        public getSourceRequest(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSourceResponse", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class getSourceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.ServiceReference1.source @return;
        
        public getSourceResponse() {
        }
        
        public getSourceResponse(ConsoleApplication1.ServiceReference1.source @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addInfoSet", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class addInfoSetRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string sourceId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ConsoleApplication1.ServiceReference1.infoSet infoSet;
        
        public addInfoSetRequest() {
        }
        
        public addInfoSetRequest(string sourceId, ConsoleApplication1.ServiceReference1.infoSet infoSet) {
            this.sourceId = sourceId;
            this.infoSet = infoSet;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addInfoSetResponse", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class addInfoSetResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public addInfoSetResponse() {
        }
        
        public addInfoSetResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addEvents", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class addEventsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://enunciate.codehaus.org/samples/full")]
        public string contributorId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string infoSetId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("assertions", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public @event[] assertions;
        
        public addEventsRequest() {
        }
        
        public addEventsRequest(string contributorId, string infoSetId, @event[] assertions) {
            this.contributorId = contributorId;
            this.infoSetId = infoSetId;
            this.assertions = assertions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addEventsResponse", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class addEventsResponse {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://enunciate.codehaus.org/samples/full")]
        public string resultOfAddingEvents;
        
        public addEventsResponse() {
        }
        
        public addEventsResponse(string resultOfAddingEvents) {
            this.resultOfAddingEvents = resultOfAddingEvents;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface sourceserviceChannel : ConsoleApplication1.ServiceReference1.sourceservice, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class sourceserviceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.sourceservice>, ConsoleApplication1.ServiceReference1.sourceservice {
        
        public sourceserviceClient() {
        }
        
        public sourceserviceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sourceserviceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sourceserviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sourceserviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void ConsoleApplication1.ServiceReference1.sourceservice.addSource(ConsoleApplication1.ServiceReference1.addSource request) {
            base.Channel.addSource(request);
        }
        
        public void addSource(ConsoleApplication1.ServiceReference1.source source) {
            ConsoleApplication1.ServiceReference1.addSource inValue = new ConsoleApplication1.ServiceReference1.addSource();
            inValue.source = source;
            ((ConsoleApplication1.ServiceReference1.sourceservice)(this)).addSource(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.getSourceResponse ConsoleApplication1.ServiceReference1.sourceservice.getSource(ConsoleApplication1.ServiceReference1.getSourceRequest request) {
            return base.Channel.getSource(request);
        }
        
        public ConsoleApplication1.ServiceReference1.source getSource(string id) {
            ConsoleApplication1.ServiceReference1.getSourceRequest inValue = new ConsoleApplication1.ServiceReference1.getSourceRequest();
            inValue.id = id;
            ConsoleApplication1.ServiceReference1.getSourceResponse retVal = ((ConsoleApplication1.ServiceReference1.sourceservice)(this)).getSource(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.addInfoSetResponse ConsoleApplication1.ServiceReference1.sourceservice.addInfoSet(ConsoleApplication1.ServiceReference1.addInfoSetRequest request) {
            return base.Channel.addInfoSet(request);
        }
        
        public string addInfoSet(string sourceId, ConsoleApplication1.ServiceReference1.infoSet infoSet) {
            ConsoleApplication1.ServiceReference1.addInfoSetRequest inValue = new ConsoleApplication1.ServiceReference1.addInfoSetRequest();
            inValue.sourceId = sourceId;
            inValue.infoSet = infoSet;
            ConsoleApplication1.ServiceReference1.addInfoSetResponse retVal = ((ConsoleApplication1.ServiceReference1.sourceservice)(this)).addInfoSet(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.addEventsResponse ConsoleApplication1.ServiceReference1.sourceservice.addEvents(ConsoleApplication1.ServiceReference1.addEventsRequest request) {
            return base.Channel.addEvents(request);
        }
        
        public string addEvents(string contributorId, string infoSetId, @event[] assertions) {
            ConsoleApplication1.ServiceReference1.addEventsRequest inValue = new ConsoleApplication1.ServiceReference1.addEventsRequest();
            inValue.contributorId = contributorId;
            inValue.infoSetId = infoSetId;
            inValue.assertions = assertions;
            ConsoleApplication1.ServiceReference1.addEventsResponse retVal = ((ConsoleApplication1.ServiceReference1.sourceservice)(this)).addEvents(inValue);
            return retVal.resultOfAddingEvents;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://enunciate.codehaus.org/samples/full", ConfigurationName="ServiceReference1.PersonService")]
    public interface PersonService {
        
        // CODEGEN: Generating message contract since the operation storePerson is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(assertion))]
        ConsoleApplication1.ServiceReference1.storePersonResponse storePerson(ConsoleApplication1.ServiceReference1.storePersonRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference1.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(assertion))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ConsoleApplication1.ServiceReference1.readPersonsResponse readPersons(ConsoleApplication1.ServiceReference1.readPersonsRequest request);
        
        // CODEGEN: Parameter 'personId' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(ConsoleApplication1.ServiceReference1.ServiceException), Action="", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(assertion))]
        ConsoleApplication1.ServiceReference1.deletePersonResponse deletePerson(ConsoleApplication1.ServiceReference1.deletePersonRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        public ConsoleApplication1.ServiceReference1.person storePerson;
        
        public storePersonRequest() {
        }
        
        public storePersonRequest(ConsoleApplication1.ServiceReference1.person storePerson) {
            this.storePerson = storePerson;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class storePersonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="storePersonResponse", Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        public ConsoleApplication1.ServiceReference1.person storePersonResponse1;
        
        public storePersonResponse() {
        }
        
        public storePersonResponse(ConsoleApplication1.ServiceReference1.person storePersonResponse1) {
            this.storePersonResponse1 = storePersonResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readPersons", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class readPersonsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("personIds", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] personIds;
        
        public readPersonsRequest() {
        }
        
        public readPersonsRequest(string[] personIds) {
            this.personIds = personIds;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="readPersonsResponse", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class readPersonsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public person[] @return;
        
        public readPersonsResponse() {
        }
        
        public readPersonsResponse(person[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deletePerson", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class deletePersonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://enunciate.codehaus.org/samples/full", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string personId;
        
        public deletePersonRequest() {
        }
        
        public deletePersonRequest(string personId) {
            this.personId = personId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="deletePersonResponse", WrapperNamespace="http://enunciate.codehaus.org/samples/full", IsWrapped=true)]
    public partial class deletePersonResponse {
        
        public deletePersonResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface PersonServiceChannel : ConsoleApplication1.ServiceReference1.PersonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class PersonServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.ServiceReference1.PersonService>, ConsoleApplication1.ServiceReference1.PersonService {
        
        public PersonServiceClient() {
        }
        
        public PersonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.storePersonResponse ConsoleApplication1.ServiceReference1.PersonService.storePerson(ConsoleApplication1.ServiceReference1.storePersonRequest request) {
            return base.Channel.storePerson(request);
        }
        
        public ConsoleApplication1.ServiceReference1.person storePerson(ConsoleApplication1.ServiceReference1.person storePerson1) {
            ConsoleApplication1.ServiceReference1.storePersonRequest inValue = new ConsoleApplication1.ServiceReference1.storePersonRequest();
            inValue.storePerson = storePerson1;
            ConsoleApplication1.ServiceReference1.storePersonResponse retVal = ((ConsoleApplication1.ServiceReference1.PersonService)(this)).storePerson(inValue);
            return retVal.storePersonResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.readPersonsResponse ConsoleApplication1.ServiceReference1.PersonService.readPersons(ConsoleApplication1.ServiceReference1.readPersonsRequest request) {
            return base.Channel.readPersons(request);
        }
        
        public person[] readPersons(string[] personIds) {
            ConsoleApplication1.ServiceReference1.readPersonsRequest inValue = new ConsoleApplication1.ServiceReference1.readPersonsRequest();
            inValue.personIds = personIds;
            ConsoleApplication1.ServiceReference1.readPersonsResponse retVal = ((ConsoleApplication1.ServiceReference1.PersonService)(this)).readPersons(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApplication1.ServiceReference1.deletePersonResponse ConsoleApplication1.ServiceReference1.PersonService.deletePerson(ConsoleApplication1.ServiceReference1.deletePersonRequest request) {
            return base.Channel.deletePerson(request);
        }
        
        public void deletePerson(string personId) {
            ConsoleApplication1.ServiceReference1.deletePersonRequest inValue = new ConsoleApplication1.ServiceReference1.deletePersonRequest();
            inValue.personId = personId;
            ConsoleApplication1.ServiceReference1.deletePersonResponse retVal = ((ConsoleApplication1.ServiceReference1.PersonService)(this)).deletePerson(inValue);
        }
    }
}
