[#ftl]
[#-- @implicitly included --]
[#macro file name charset="utf-8"]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#macro]
[#function prefix ns]
  [#stop "Should never be called."/]
[/#function]
[#function isFacetExcluded hasFacets]
  [#stop "Should never be called."/]
[/#function]
[#function isDefinedGlobally element]
  [#stop "Should never be called."/]
[/#function]
[#function qnameForType typeMirror]
  [#stop "Should never be called."/]
[/#function]
[#function accessorOverridesAnother accessor]
  [#stop "Should never be called."/]
[/#function]