<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>

<head>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
  <link rel="stylesheet" type="text/css" href="<c:url value="${cssURL}"/>" media="screen"/>
  <title>Confirm Access</title>
</head>

<body>

<div class="container">

  <div class="main">

    <div class="header">

      <div class="title">
        <h1>Confirm Access</h1>
      </div>

    </div>

    <div class="widecontent">

      <h2>Please Confirm</h2>

      <p>You hereby grant access to <b><c:out value="${consumer.displayName}"/></b> to access <b><c:out value="${consumer.resourceName}" default="your protected resources"/></b>. <c:out value="${consumer.resourceDescription}"/></p>

      <div align="center">
        <form action="<c:url value="${grantAccessURL}"/>" method="POST">
          <input type="hidden" name="oauth_token" value="<c:out value="${oauth_token}"/>"/>
          <c:if test="${!empty oauth_callback}">
            <input type="hidden" name="oauth_callback" value="<c:out value="${oauth_callback}"/>"/>
          </c:if>
          <input type="submit" value="confirm"/>
        </form>
      </div>

    </div>

    <div class="clearer"><span></span></div>

  </div>

  <div class="footer">Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a
    href="http://validator.w3.org/check?uri=referer">XHTML</a>. Generated by
    <a href="http://enunciate.codehaus.org">Enunciate</a>. Template design by <a href="http://templates.arcsin.se">Arcsin</a>
  </div>

</div>

</body>

</html>