<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %>
<html>

<head>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
  <link rel="stylesheet" type="text/css" href="<c:url value="${cssURL}"/>" media="screen"/>
  <title>Login</title>
</head>

<body>

<div class="container">

	<div class="main">

		<div class="header">

			<div class="title">
				<h1>Login</h1>
			</div>

		</div>

		<div class="widecontent">
      <c:if test="${!empty sessionScope.ACEGI_SECURITY_LAST_EXCEPTION}">
        <p class="errortext"><c:out value="${sessionScope.ACEGI_SECURITY_LAST_EXCEPTION.message}" default="Your login attempt was unsuccessful."/></p>
        <c:remove scope="session" var="ACEGI_SECURITY_LAST_EXCEPTION"/>
      </c:if>

      <form action="<c:url value="${formLoginURL}"/>" method="POST">
        <p>username<br/>
        <input type="text" name="j_username"/></p>
        <p>password<br/>
        <input type="password" name="j_password"/></p>
        <input type="submit" value="login"/>
      </form>

		</div>

		<div class="clearer"><span></span></div>

	</div>

	<div class="footer">Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a href="http://validator.w3.org/check?uri=referer">XHTML</a>. Generated by
    <a href="http://enunciate.codehaus.org">Enunciate</a>. Template design by <a href="http://templates.arcsin.se">Arcsin</a>
	</div>

</div>

</body>

</html>