[#ftl]
[#-- @implicitly included --]
[#macro file name charset="utf-8"]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#macro]
[#function isFacetExcluded element]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function namespaceFor element]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function simpleNameFor type params=true]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function classnameFor element params=true]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function accessorOverridesAnother accessor]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function requestDocumentQName webMethod]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function responseDocumentQName webMethod]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function listsAsArraysClassnameFor webResult]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]
[#function findRootElement enumTypeDefinition]
  [#--this template is here just so Intellij knows there exists a macro named "file".--]
  [#--it's just for developer support and shouldn't be needed at runtime.--]
  [#stop "Should never be called."/]
[/#function]