<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN"
  "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html>

<head>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
  <link rel="stylesheet" type="text/css" href="<c:url value="${cssURL}"/>" media="screen"/>
  <title>Access Confirmed</title>
</head>

<body>

<div class="container">

  <div class="main">

    <div class="header">

      <div class="title">
        <h1>Access Confirmed</h1>
      </div>

    </div>

    <div class="widecontent">

      <h2>Access Confirmed</h2>

      <p>You have successfully granted access to your protected resources.</p>

    </div>

    <div class="clearer"><span></span></div>

  </div>

  <div class="footer">Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a
    href="http://validator.w3.org/check?uri=referer">XHTML</a>. Generated by
    <a href="http://enunciate.codehaus.org">Enunciate</a>. Template design by <a href="http://templates.arcsin.se">Arcsin</a>
  </div>

</div>

</body>

</html>