<%@ taglib prefix="c" uri="http://java.sun.com/jstl/core" %>
<html>

<head>
  <meta http-equiv="content-type" content="text/html; charset=iso-8859-1"/>
  <link rel="stylesheet" type="text/css" href="<c:url value="${cssURL}"/>" media="screen"/>
  <title>OAuth</title>
</head>

<body>

<div class="container">

  <div class="main">

    <div class="header">

      <div class="title">
        <h1>OAuth</h1>
      </div>

    </div>

    <div class="widecontent">

      <p>Certain services are protected via <a href="http://oauth.net">OAuth</a>. To be enabled to use OAuth to access these services, you must first register
        as a consumer. Once registered, the following information is used to correctly exercise the OAuth API:</p>

      <div align="center">
        <table>
          <tr>
            <td align="right">Request Token URL:</td>
            <td><a href="<c:url value="${request_token_url}"/>"><c:url value="${request_token_url}"/></a></td>
          </tr>
          <tr>
            <td align="right">Access Token URL:</td>
            <td><a href="<c:url value="${access_token_url}"/>"><c:url value="${access_token_url}"/></a></td>
          </tr>
          <tr>
            <td align="right">User Authorization Entry Point:</td>
            <td><a href="<c:url value="${confirm_access_url}"/>"><c:url value="${confirm_access_url}"/></a></td>
          </tr>
        </table>
      </div>

    </div>

    <div class="clearer"><span></span></div>

  </div>

  <div class="footer">Valid <a href="http://jigsaw.w3.org/css-validator/check/referer">CSS</a> &amp; <a
    href="http://validator.w3.org/check?uri=referer">XHTML</a>. Generated by
    <a href="http://enunciate.sourceforge.net">Enunciate</a>. Template design by <a href="http://templates.arcsin.se">Arcsin</a>
  </div>

</div>

</body>

</html>